---
title: "ma350-lab5-RG-ML-SC"
author: "RG, Matt Lawson, and Sam Cavalli"
date: "3/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Git and GitHub

## 0

https://github.com/rmgreenstone/ma350-lab5-RG-ML-SC.git

# Finding Outliers Using Tukey’s Rule-of-Thumb

## Data


```{r}

x <- c(2.2, 7.8, -4.4, 0.0, -1.2, 3.9, 4.9, -5.7, -7.9, -4.9, 28.7, 4.9)
      
```


## 1



```{r}
quantile(x)
sort(x)
quant.4 <- quantile(x)[4]
quant.2 <- quantile(x)[2]
quant.4-quant.2
```

The first quartile is -4.525, the second quartile is 1.1 and the third quartile is 4.9. The interquartile range of x is Q3 - Q1 which is 9.425.I know these values are all correct based off arithmetic. 


## 2



```{r}
quartiles <- function(X){

  the.quantiles <- quantile(X)
  quant.one <- quantile(X)[2]
  quant.three <- quantile(X)[4]
  inter <- quant.three-quant.one
  
   quart.vector<- c(quant.one, quant.three, inter)
  names(quart.vector) <- c("1st Quartile", "3rd Quartile", "Interquartile Range")
  

  return(quart.vector)
 
}
quartiles(x)
```



## 3



By inspection, 28.7 will be the only outlier.



## 4



```{r}
tukey.outlier <- function(x){
  outlier <- vector(length = length(x))
  for (i in 1:length(x)) {
    if(x[i] < quartiles(x)[1]-1.5*quartiles(x)[3] | x[i] > quartiles(x)[2]+1.5*quartiles(x)[3]){
      outlier[i] <- TRUE
    } else {
      outlier[i] <- FALSE
    }
  }
  return(outlier)
}

tukey.outlier(x)
```



## 5


```{r}
test.tukey.outlier <- function(tukey.outlier) {
  
}
```



## 6



```{r}
-x
```



## 7



```{r}

```



## 8



```{r}

```



## 9



```{r}

```



## 10



```{r}

```



## 11



```{r}

```




